# Generated by Django 5.2.17 on 2026-09-28 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('numero_permis', models.CharField(max_length=50, unique=True, verbose_name='Numéro de permis')),
                ('date_expiration_permis', models.DateField(verbose_name='Expiration du permis')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Chauffeur',
                'verbose_name_plural': 'Chauffeurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(help_text='Format béninois, par exemple AB 1234 RB', max_length=20, unique=True, verbose_name='Immatriculation')),
                ('marque', models.CharField(max_length=50, verbose_name='Marque')),
                ('modele', models.CharField(max_length=50, verbose_name='Modèle')),
                ('annee', models.PositiveIntegerField(verbose_name='Année de mise en circulation')),
                ('type_vehicule', models.CharField(choices=[('camion', 'Camion'), ('utilitaire', 'Utilitaire'), ('voiture', 'Voiture'), ('moto', 'Moto')], max_length=20, verbose_name='Type de véhicule')),
                ('kilometrage', models.PositiveIntegerField(default=0, verbose_name='Kilométrage')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('en_mission', 'En mission'), ('en_maintenance', 'En maintenance'), ('hors_service', 'Hors service')], default='disponible', max_length=20, verbose_name='Statut')),
                ('date_fin_assurance', models.DateField(verbose_name="Fin de l'assurance")),
                ('date_visite_technique', models.DateField(verbose_name='Prochaine visite technique')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['immatriculation'],
            },
        ),
        migrations.CreateModel(
            name='PleinCarburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du plein')),
                ('litres', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Litres')),
                ('prix_litre', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix du litre (FCFA)')),
                ('km_compteur', models.PositiveIntegerField(help_text='Relevé du compteur au moment du plein', verbose_name='Kilométrage au compteur')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pleins', to='fleet.chauffeur', verbose_name='Chauffeur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pleins', to='fleet.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Plein de carburant',
                'verbose_name_plural': 'Pleins de carburant',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=100, verbose_name='Lieu de départ')),
                ('destination', models.CharField(max_length=100, verbose_name='Destination')),
                ('date_depart', models.DateField(verbose_name='Date de départ')),
                ('date_arrivee', models.DateField(blank=True, null=True, verbose_name="Date d'arrivée")),
                ('km_depart', models.PositiveIntegerField(verbose_name='Kilométrage au départ')),
                ('km_arrivee', models.PositiveIntegerField(blank=True, null=True, verbose_name="Kilométrage à l'arrivée")),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='fleet.chauffeur', verbose_name='Chauffeur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='fleet.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['-date_depart'],
            },
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entretien', models.CharField(choices=[('vidange', 'Vidange'), ('pneus', 'Pneus'), ('freins', 'Freins'), ('autre', 'Autre')], max_length=20, verbose_name="Type d'entretien")),
                ('date', models.DateField(verbose_name="Date de l'intervention")),
                ('km', models.PositiveIntegerField(verbose_name="Kilométrage à l'intervention")),
                ('cout', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Coût (FCFA)')),
                ('prestataire', models.CharField(max_length=100, verbose_name='Prestataire')),
                ('prochaine_echeance_km', models.PositiveIntegerField(blank=True, help_text='Kilométrage auquel le prochain entretien est attendu', null=True, verbose_name='Prochaine échéance (km)')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entretiens', to='fleet.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Entretien',
                'verbose_name_plural': 'Entretiens',
                'ordering': ['-date'],
            },
        ),
    ]
