# Generated by Django 5.2.17 on 2026-09-30 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('assurance', 'Assurance'), ('visite_technique', 'Visite technique'), ('carte_grise', 'Carte grise'), ('licence_transport', 'Licence de transport'), ('autre', 'Autre')], max_length=30, verbose_name='Type de document')),
                ('numero', models.CharField(blank=True, max_length=100, verbose_name='Numéro de la pièce')),
                ('date_emission', models.DateField(blank=True, null=True, verbose_name="Date d'émission")),
                ('date_expiration', models.DateField(blank=True, help_text='À laisser vide pour une pièce sans échéance, comme la carte grise', null=True, verbose_name="Date d'expiration")),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_expiration'],
            },
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='date_fin_assurance',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='date_visite_technique',
        ),
        migrations.AddConstraint(
            model_name='mission',
            constraint=models.CheckConstraint(condition=models.Q(('km_arrivee__isnull', True), ('km_arrivee__gt', models.F('km_depart')), _connector='OR'), name='mission_km_arrivee_superieur_km_depart', violation_error_message="Le kilométrage d'arrivée doit être strictement supérieur au kilométrage de départ."),
        ),
        migrations.AddConstraint(
            model_name='mission',
            constraint=models.CheckConstraint(condition=models.Q(('date_arrivee__isnull', True), ('date_arrivee__gte', models.F('date_depart')), _connector='OR'), name='mission_date_arrivee_apres_date_depart', violation_error_message="La date d'arrivée ne peut pas précéder la date de départ."),
        ),
        migrations.AddConstraint(
            model_name='pleincarburant',
            constraint=models.CheckConstraint(condition=models.Q(('litres__gt', 0)), name='plein_litres_strictement_positifs', violation_error_message='Le nombre de litres doit être strictement positif.'),
        ),
        migrations.AddField(
            model_name='document',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='fleet.vehicule', verbose_name='Véhicule'),
        ),
    ]
