# Generated by Django 5.2.17 on 2026-10-01 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_document_et_contraintes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicule',
            options={'ordering': ['immatriculation'], 'verbose_name': 'Camion', 'verbose_name_plural': 'Camions'},
        ),
        migrations.AlterField(
            model_name='document',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='fleet.vehicule', verbose_name='Camion'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entretiens', to='fleet.vehicule', verbose_name='Camion'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='fleet.vehicule', verbose_name='Camion'),
        ),
        migrations.AlterField(
            model_name='pleincarburant',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pleins', to='fleet.vehicule', verbose_name='Camion'),
        ),
    ]
