# Generated by Django 5.2.17 on 2026-10-01 12:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_libelle_camion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FournisseurGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60, unique=True, verbose_name='Nom')),
                ('statut_connexion', models.CharField(choices=[('connecte', 'Connecté'), ('en_attente', 'En attente'), ('erreur', 'Erreur')], default='en_attente', max_length=20, verbose_name='Statut du raccordement')),
                ('frequence_secondes', models.PositiveIntegerField(default=30, help_text='Intervalle entre deux relevés de position chez ce fournisseur', verbose_name="Fréquence d'interrogation (s)")),
                ('dernier_echange', models.DateTimeField(blank=True, null=True, verbose_name='Dernier échange réussi')),
            ],
            options={
                'verbose_name': 'Fournisseur GPS',
                'verbose_name_plural': 'Fournisseurs GPS',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='vehicule',
            name='boitier_id',
            field=models.CharField(blank=True, help_text='Référence du boîtier chez le fournisseur, par exemple CT-88214', max_length=40, verbose_name='Identifiant du boîtier'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='direction',
            field=models.SmallIntegerField(choices=[(1, 'Aller'), (-1, 'Retour')], default=1, verbose_name='Sens de parcours'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='itineraire',
            field=models.CharField(blank=True, choices=[('cotonou_parakou', 'Cotonou → Parakou (RNIE 2)'), ('cotonou_porto_novo', 'Cotonou → Porto-Novo'), ('cotonou_lokossa', 'Cotonou → Lokossa')], max_length=30, verbose_name='Itinéraire simulé'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='progression',
            field=models.FloatField(default=0, help_text="0 au départ, 1 à l'arrivée", verbose_name="Progression sur l'itinéraire"),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='signal_coupe',
            field=models.BooleanField(default=False, help_text='Simule un boîtier qui ne remonte plus rien', verbose_name='Signal coupé'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='vitesse_nominale_kmh',
            field=models.PositiveIntegerField(default=60, verbose_name='Vitesse nominale (km/h)'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='fournisseur_gps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='fleet.fournisseurgps', verbose_name='Fournisseur GPS'),
        ),
        migrations.CreateModel(
            name='PositionGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('vitesse_kmh', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Vitesse (km/h)')),
                ('horodatage', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Horodatage')),
                ('source', models.CharField(choices=[('simulation', 'Simulation'), ('webhook', 'Webhook fournisseur')], default='simulation', max_length=20, verbose_name='Source')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='fleet.vehicule', verbose_name='Camion')),
            ],
            options={
                'verbose_name': 'Position GPS',
                'verbose_name_plural': 'Positions GPS',
                'ordering': ['-horodatage', '-pk'],
                'indexes': [models.Index(fields=['vehicule', '-horodatage'], name='position_vehicule_recent')],
            },
        ),
    ]
