# Generated by Django 5.2.17 on 2026-10-01 13:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_socle_gps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('sans_signal', 'Boîtier sans signal'), ('echeance', 'Échéance')], max_length=20, verbose_name="Type d'alerte")),
                ('message', models.TextField(verbose_name='Message')),
                ('ouverte_le', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ouverte le')),
                ('resolue_le', models.DateTimeField(blank=True, null=True, verbose_name='Résolue le')),
                ('email_envoye_le', models.DateTimeField(blank=True, null=True, verbose_name='E-mail envoyé le')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='fleet.chauffeur', verbose_name='Chauffeur')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='fleet.document', verbose_name='Document')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='fleet.vehicule', verbose_name='Camion')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['resolue_le', '-ouverte_le'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('resolue_le__isnull', True), ('vehicule__isnull', False)), fields=('type_alerte', 'vehicule'), name='une_alerte_ouverte_par_camion'), models.UniqueConstraint(condition=models.Q(('chauffeur__isnull', False), ('resolue_le__isnull', True)), fields=('type_alerte', 'chauffeur'), name='une_alerte_ouverte_par_chauffeur'), models.UniqueConstraint(condition=models.Q(('document__isnull', False), ('resolue_le__isnull', True)), fields=('type_alerte', 'document'), name='une_alerte_ouverte_par_document')],
            },
        ),
    ]
