# Generated by Django 5.2.17 on 2026-10-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_alertes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte',
            field=models.CharField(choices=[('sans_signal', 'Boîtier sans signal'), ('echeance', 'Pièce à renouveler'), ('echeance_permis', 'Permis à renouveler')], max_length=20, verbose_name="Type d'alerte"),
        ),
    ]
