"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ
from django.contrib.messages import constants as messages_constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Lecture des variables d'environnement depuis le fichier .env (non versionne).
env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # humanize fait partie de Django, ce n'est pas une dependance nouvelle.
    # On s'en sert pour intcomma, qui en locale fr-fr separe les milliers par
    # une espace insecable : 1 240 000 au lieu de 1240000.
    'django.contrib.humanize',
    'fleet',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "fleet.context_processors.navigation",
                "fleet.context_processors.alertes",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# E-mail
# https://docs.djangoproject.com/en/5.2/topics/email/

# Par defaut, les e-mails sont ECRITS DANS LA CONSOLE et n'arrivent nulle
# part. C'est le defaut prudent : en developpement on veut lire le message,
# pas le livrer, et surtout on ne veut pas qu'un envoi reel parte par
# accident pendant une demonstration. Passer en SMTP est une decision
# explicite, prise dans le .env.
EMAIL_BACKEND = env(
    "EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = env("EMAIL_HOST", default="")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)

# L'expediteur affiche. Un domaine .invalid garantit qu'aucune reponse ne
# partira vers une vraie boite tant que le projet n'a pas son domaine.
DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL", default="FleetFlow <ne-pas-repondre@fleetflow.invalid>"
)

# Destinataire des alertes et du rapport quotidien. Vide par defaut : les
# services et les commandes doivent le dire clairement plutot que d'envoyer
# dans le vide.
FLEETFLOW_EMAIL_GERANT = env("FLEETFLOW_EMAIL_GERANT", default="")


# Suivi GPS
# --------------------------------------------------------------------------

# Duree, en minutes, au-dela de laquelle un boitier qui ne remonte plus rien
# est declare « sans signal ». Reglable par l'environnement : la demonstration
# l'abaisse a 1 pour qu'on n'attende pas une demi-heure devant l'ecran.
FLEETFLOW_SEUIL_SANS_SIGNAL_MIN = env.int("FLEETFLOW_SEUIL_SANS_SIGNAL_MIN", default=30)

# Fond de carte de la page Carte. **Vide par defaut, et c'est voulu.**
#
# Les tuiles sont la seule chose qu'on ne peut pas servir en local : celles du
# Benin representent plusieurs gigaoctets. Mais les serveurs d'OpenStreetMap
# sont tenus par des benevoles, et leur politique d'usage interdit ce genre de
# dependance — ils renvoient alors une image « Access blocked » a la place de
# chaque tuile. C'est arrive en developpement, et c'est la raison de ce
# reglage.
#
# Sans adresse, la carte affiche les itineraires et les camions sur un aplat
# neutre : elle reste utilisable, et l'application ne depend d'aucun service
# exterieur. Avec une adresse, le fond apparait. Le choix du fournisseur — et
# le droit de s'en servir — appartient a celui qui deploie.
FLEETFLOW_TUILES_URL = env("FLEETFLOW_TUILES_URL", default="")
FLEETFLOW_TUILES_ATTRIBUTION = env("FLEETFLOW_TUILES_ATTRIBUTION", default="")


# Messages
# https://docs.djangoproject.com/en/5.2/ref/contrib/messages/

# Django etiquette ses messages d'erreur "error" ; Bootstrap attend la classe
# "alert-danger". Renommer la categorie ici evite d'ecrire un if dans chaque
# gabarit qui affiche des messages.
# Les categories de Django sont renommees directement en tons du theme.
# Le gabarit ecrit alors « ff-bandeau--{{ message.tags }} » et ne decide
# d'aucune couleur : la correspondance vit ici, en un seul endroit.
MESSAGE_TAGS = {
    messages_constants.DEBUG: "neutre",
    messages_constants.INFO: "neutre",
    messages_constants.SUCCESS: "vert",
    messages_constants.WARNING: "ambre",
    messages_constants.ERROR: "rouge",
}


# Authentification
# https://docs.djangoproject.com/en/5.2/topics/auth/default/

# Vers quelle page @login_required / LoginRequiredMixin renvoie un visiteur
# non connecte. C'est le nom de route fourni par django.contrib.auth.urls.
LOGIN_URL = "login"

# Apres une connexion reussie, on arrive sur la liste des vehicules : le
# tableau de bord avec indicateurs n'existe pas encore (prevu plus tard).
# Django resout ce nom de route au moment de la redirection, pas au demarrage :
# la route peut donc etre definie plus tard sans casser le projet.
LOGIN_REDIRECT_URL = "fleet:vehicule_liste"

# Apres une deconnexion, retour au formulaire de connexion.
LOGOUT_REDIRECT_URL = "login"


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "Africa/Porto-Novo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Les fichiers du theme et les ressources rapatriees (Bootstrap, icones,
# polices) vivent dans static/ a la racine du projet. STATICFILES_DIRS les
# declare a Django ; en DEBUG, le serveur de developpement les sert seul.
# En production il faudra un collectstatic et un serveur de fichiers : note
# au BACKLOG.
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
